# Generated by Django 2.1.1 on 2018-10-02 15:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pastebin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_update',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='POST update datetime'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='url',
            name='url_update',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='URL update datetime'),
            preserve_default=False,
        ),
    ]
