# Generated by Django 2.1.1 on 2018-10-03 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastebin', '0003_auto_20181003_0722'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='url',
            field=models.CharField(default=12345, max_length=15),
            preserve_default=False,
        ),
    ]
