# Generated by Django 2.1.1 on 2018-10-11 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastebin', '0007_post_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_info',
            field=models.TextField(max_length=2000),
        ),
    ]
