# Generated by Django 2.1.1 on 2018-10-11 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastebin', '0008_auto_20181011_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='file_path',
            field=models.CharField(default='asdf', max_length=500),
            preserve_default=False,
        ),
    ]
