# Generated by Django 2.1.1 on 2018-10-12 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastebin', '0009_post_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='Untitled', max_length=30),
        ),
    ]
